package com.chientt.myredis;

import java.io.File;
import java.util.List;
import java.util.concurrent.locks.Lock;

public class RedisServer {
    final static int ANET_ERR_LEN = 256;
   public Thread mainThread;
    public  int port;
    public String bindAddr;
    public String unixSocket;
    public  int ipfd;
    public     int sofd;
    public     RedisDb redisDb;
    public     long dirty;
    public long dirtyBeforeBackgroundSave;
    public List<Object> clients;
    public     Dict commands;
    public boolean loading;
    public long loadingTotalBytes;
    public long loadingLoadedBytes;
    public long loadingStartTime;
    public RedisCommand delCommand;
    public RedisCommand multiCommand;
    public List<Object> slaves;
    public List<Object> monitors;
    public char[] netError = new char[ANET_ERR_LEN];
    public AeEventLoop eventLoop;
    public int cronLoops;
    public long lastSave;
    public long startTimeStat;
    public long numCommandsStat;
    public long numConnectionsStat;
    public long expiredKeysStat;
    public long evictedKeysStat;
    public long keyspaceHitsStat;
    public long keyspaceMissesStat;
    public List<Object> slowLog;
    public long slowLogEntryId;
    public long slowLogLogSlowerThan;
    public long slowLogMaxLen;

    //configuration
    public int verbosity;
    public int maxIdLeTime;
    public int dbNum;
    public int daemonSize;
    public boolean appendOnly;
    public int appendFsync;
    public int noAppendFsyncOnRewrite;
    public int shutdownAsap;
    public long lastFSync;
    public     int appendFd;
    public     int appendSelDb;
    public String pidFile;
    public int bgSaveChildPid;
    public int bgRewriteChildPid;
    public String bgRewriteBuf;
    public String aofBuf;
    public SaveParam saveParam;
    public int saveParamLen;
    public String logFile;
    public int syslogEnabled;
    public String syslogIdent;
    public int syslogFacility;
    public String dbFileName;
    public String appendFileName;
    public String requirePass;
    public int rdbCompress;
    public int activeReharshing;
    public int isSlave;
    public String masterAuth;
    public String masterHost;
    public int masterPort;
    public RedisClient master;
    public int replState;
    public long replTransferLeft;
    public int replTransferS;
    public int replTransferFd;
    public String replTranferTmpFile;
    public long replTransferLastIo;
    public int replServerStateData;
    public int maxClients;
    public long maxMemory;
    public int maxMemoryPolicy;
    public int maxMemorySamples;
    public int bpopBlockedClients;
    public int vmBlockedClients;
    public List unblockedClients;
    public int sortDesc;
    public int sortAplha;
    public int sortByPattern;
    public boolean vmEnabled;
    public String vmSwapFile;
    public long vmPageSize;
    public long vmPages;
    public long vmMaxMemory;
    public long hashMaxZipMapEntries;
    public long hashMapZipMapValue;
    public long listMaxZipListEntries;
    public long listMaxZipListValue;
    public long setMaxIntsetEntries;
    public File vmFp;
    public     int vmFd;
    public long vmNextpage;
    public long vmNearPages;
    public String vmBitmap;
    public long unixTime;
    public List ioNewJobs;
    public List ioProcessing;
    public List ioProcessed;
    public List ioReadyClients;
    public Lock ioMutex;
    public Lock ioSwapFileMutex;
    public Lock ioThreadsAttr;
    public int ioActiveThreads;
    public int vmMaxThreads;
    public int ioReadyPipeRead;
    public int ioReadyPipeWrite;
    public long vmStatsUsagePage;
    public long vmStatsSwappedObjects;
    public long vmStatsSwapouts;
    public long vmStatsIns;
    public Dict pubsubChannels;
    public List pubsubPattern;
    public long lrulock = 22;
    public long lrulockPadding = 10;

}
